- shell++:
  - description: Install Linuxbrew
    condition: '! hash brew 2>/dev/null || test -h $(which brew)'
  - stdout: true
    stderr: true
    command: |
      PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"
      sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
      echo 'export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"' >>~/.bashrc
      echo 'export MANPATH="/home/linuxbrew/.linuxbrew/share/man:$MANPATH"' >>~/.bashrc
      echo 'export INFOPATH="/home/linuxbrew/.linuxbrew/share/info:$INFOPATH"' >>~/.bashrc
      echo Linuxbrew prefix $(brew --prefix)
