- shell++:
  - description: Setting OSX defaults
    condition: 'true'
  - stdout: true
    stdin: true
    stderr: true
    command: |
      . ~/.dotfiles/apps/misc/macos/settings

# # iTerm 2 Shell integration
# curl -L https://iterm2.com/misc/install_shell_integration.sh | bash
